### ISSUE TITLE
Provide a delete API for deleting a schema metadata and all related information

### ISSUE THREAD

**Issue by priyank5485** [hortonworks/registry#509] opened 2018-11-13 02:57 UTC
Currently, we do not support deleting a schema metadata at top level. This issue is created to provide such an API that will delete schema metadata  and all related data including versions, states, branches, mappings, etc. We will need to add a corresponding UI control and a warning message for the same before UI makes this API call.

**Comment by priyank5485** [comment] 2018-11-13 03:00
https://github.com/hortonworks/registry/pull/510

**Comment by kamalcph** [comment] 2019-02-19 16:28
@priyank5485 
This feature is not exposed via UI.  Can you add documentation for this feature?

https://registry-project.readthedocs.io/en/latest/schema-registry.html#using-schema-related-apis

**Comment by priyank5485** [comment] 2019-02-20 01:11
@kamalcph I have added the API usage in https://github.com/hortonworks/registry/commit/6fa81bccecbac06b7976a434a43d9e8017d4b238

@satishd I pushed a commit to master branch only.  Given that docs are not part of release artifacts, we should be good. But checking with you just in case we have documentation per release.

**Comment by satishd** [comment] 2019-02-20 02:56
>@satishd I pushed a commit to master branch only. Given that docs are not part of release artifacts, we should be good. But checking with you just in case we have documentation per release.

Agree on that. Generally, users look at readthedocs which shows by default with `master` branch. I do not think we need to create a new RC to have this in 0.6.0 version as it is minor doc issue.

**Comment by satishd** [comment] 2019-02-20 02:58
@kamalcph We plan to have this feature via UI once it is covered by QE tests and tested thoroughly. REST API can be used by users who wants to still use delete functionality but this can be considered as experimental.

**Comment by gcsaba2** [comment] 2022-10-05 13:04
Duplicate of #510

**Closed by gcsaba2** 2022-10-05 13:04 UTC
